# Generated by Django 4.1.5 on 2023-02-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0006_rename_username_registeration_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registeration',
        ),
    ]
