# Generated by Django 4.1.5 on 2023-03-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0005_cart_price_cart_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_image',
            field=models.ImageField(default='null.jpeg', upload_to='sample'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.registeration'),
        ),
    ]
