# Generated by Django 4.1.5 on 2023-03-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0006_cart_product_image_cart_status_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_image',
        ),
    ]
