# Generated by Django 4.1.5 on 2023-03-03 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0007_remove_cart_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.cart')),
            ],
        ),
    ]
