# Generated by Django 4.1.5 on 2023-03-03 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0008_checkout_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_data',
            name='cart_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_app.cart'),
        ),
    ]
