# Generated by Django 4.1.5 on 2023-03-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0009_alter_checkout_data_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
