# Generated by Django 4.1.5 on 2023-03-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0010_new_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_register',
            old_name='email',
            new_name='new_email',
        ),
        migrations.RenameField(
            model_name='new_register',
            old_name='password',
            new_name='new_password',
        ),
        migrations.RenameField(
            model_name='new_register',
            old_name='phone_no',
            new_name='new_phone_no',
        ),
        migrations.RenameField(
            model_name='new_register',
            old_name='status',
            new_name='new_status',
        ),
        migrations.RenameField(
            model_name='new_register',
            old_name='username',
            new_name='new_username',
        ),
    ]
