# Generated by Django 4.1.5 on 2023-03-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_app', '0011_rename_email_new_register_new_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_data',
            name='order',
            field=models.TextField(default=0),
        ),
    ]
